#!/bin/bash

TIME_SUNRISE=7
TIME_SUNSET=19
RUSH_HOUR_START=12
RUSH_HOUR_END=14

MIN_BRIGHT=27
MAX_BRIGHT=50   

SLOPE=$(echo "($MAX_BRIGHT - $MIN_BRIGHT) / ($RUSH_HOUR_START - $TIME_SUNRISE)")

# in minutes
REFRESH_TIME=5

set_bright () {
    echo Seteando brillo en $1

    backlight=$(ls /sys/class/backlight/)
	echo $1 | tee "/sys/class/backlight/$backlight/brightness"
}

get_bright () {
	HORA_ACTUAL=$(date +%H |bc)
	
    # Antes del amanecer o después de anocher
	if [[ $HORA_ACTUAL -le $TIME_SUNRISE ]] || [[ $HORA_ACTUAL -ge $TIME_SUNSET ]]; then
		BRILLO=$MIN_BRIGHT
	else
        # dentro del horario pico
		if [[ $HORA_ACTUAL -ge $RUSH_HOUR_START ]] && [[ $HORA_ACTUAL -le $RUSH_HOUR_END ]] ; then
			BRILLO=$MAX_BRIGHT
		else
            # por la mañana antes de las horas-pico
			if [[ $HORA_ACTUAL -lt $RUSH_HOUR_START ]]; then                
				BRILLO=$(echo "$MIN_BRIGHT + $SLOPE * ($HORA_ACTUAL - $TIME_SUNRISE)" |bc)
			else
				# después de las horas-pico y antes del anochecer
				BRILLO=$(echo "$MAX_BRIGHT - $SLOPE * ($HORA_ACTUAL - $RUSH_HOUR_END)" |bc)
			fi
		fi
	fi
}

SECS=$(echo "$REFRESH_TIME * 60" |bc)


while true; do
  get_bright
  set_bright $BRILLO
  sleep $SECS
done


